Task/improve hardcoded styles and types
project-error/new-phone-who-dis pull request #107
Opened 2021-02-19 00:18 UTC by jfrader

I revamped the entire messages app to not use hardcoded things and make reusable components. 

This should be the way IMO to make any custom app colors.

2021-02-19 13:12 UTC, RockySouthpaw commented
Will review this in a few hours :)

2021-02-19 17:08 UTC, RockySouthpaw reviewed
Tested in game as of this comment, everything worked fine and the UI improvements all look well.

Someone will need to review the code.

2021-02-19 20:08 UTC, jfrader commented
> Tested in game as of this comment, everything worked fine and the UI improvements all look well.
> 
> Someone will need to review the code.

@itschip @TasoOneAsia

2021-02-21 16:53 UTC, itschip requested changes

2021-02-21 16:53 UTC, itschip commented on phone/src/apps/messages/components/modal/MessageBubble.tsx
> +    width: '80%',
Let's set a min and max width on the papers, so the message 'bubble' doesn't stretch so much as it does now,

2021-02-21 16:53 UTC, itschip commented on phone/src/apps/messages/components/modal/MessageBubble.tsx
> +    width: '80%',
Let's set a min and max width on the papers, so the message 'bubble' doesn't stretch so much as it does now,

2021-02-21 16:53 UTC, itschip commented on phone/src/apps/messages/components/modal/MessageBubble.tsx
> +        <Box textAlign='right'>
Remove the styling on the Box.

2021-02-21 17:29 UTC, jfrader commented on phone/src/apps/messages/components/modal/MessageBubble.tsx
> +        <Box textAlign='right'>
Why?

2021-02-21 17:31 UTC, RockySouthpaw commented
Sellout looks a lot better now with other themes so good work on that. 

Alerts stilll have an overflow issue where if the number exceeds a certain amount it will overflow essentially. Not sure if this is out side the scope of this PR though. Error [here](https://app.gitkraken.com/glo/card/1235577709d04f95be80db677c6b8a1b)

This PR also fixes the `update` and `delete` buttons not being properly alligned anymore.
[Before(https://media.discordapp.net/attachments/791854455468458042/812081641362685952/unknown.png) [Now](https://i.imgur.com/DMw5PCR.png)

2021-02-21 17:41 UTC, itschip approved these changes
LGTM 👍

2021-02-21 17:41 UTC, merged