Tweak/messages additions (in memory of Leonard Nimoy )
project-error/new-phone-who-dis pull request #118
Opened 2021-02-27 17:29 UTC by itschip

2021-02-27 19:36 UTC, jfrader approved these changes
Nice Job!

2021-03-02 18:15 UTC, TasoOneAsia requested changes

2021-03-02 18:15 UTC, TasoOneAsia commented on phone/src/apps/messages/components/modal/Conversation.tsx
Please remove

2021-03-02 18:15 UTC, TasoOneAsia commented on resources/server/sv_messages.ts
> +  console.log(<any[]>results);
Remove console.log

2021-03-02 22:29 UTC, itschip commented
```sql
unreadCount int(11) NOT NULL DEFAULT 0,
```

This is needed in your DB for `npwd_messages_group`, if you want to test.

2021-03-03 02:40 UTC, jfrader approved these changes

2021-03-03 02:40 UTC, jfrader commented on phone/src/apps/messages/hooks/useMessageNotifications.ts
> +      app: 'MESSAGS',
```suggestion
      app: 'MESSAGES',
```

2021-03-03 02:40 UTC, jfrader commented on phone/src/os/notifications/providers/NotificationsProvider.tsx
> +      console.log(id, notifications);
```suggestion
```

2021-03-03 02:42 UTC, jfrader approved these changes

2021-03-03 02:42 UTC, jfrader commented on phone/src/common/typings/messages.ts
> +  groupName: string;
```suggestion
  groupName: string;
  groupId: string;
```

2021-03-03 02:47 UTC, jfrader approved these changes

2021-03-03 02:47 UTC, jfrader commented on phone/src/apps/messages/hooks/useMessageNotifications.ts
> +      id,
```suggestion
      id,
      sound: true,
```

2021-03-03 04:37 UTC, jfrader commented on phone/src/apps/messages/components/modal/Conversation.tsx
Done

2021-03-03 04:43 UTC, jfrader commented on resources/server/sv_messages.ts
> +    'UPDATE npwd_messages_groups SET unreadCount = 0 WHERE groupId = ? AND participant_identifier = ?';
```suggestion
    'UPDATE npwd_messages_groups SET unreadCount = 0 WHERE group_id = ? AND participant_identifier = ?';
```

2021-03-04 23:35 UTC, merged