working implementation of twitter notification preferences
project-error/new-phone-who-dis pull request #147
Opened 2021-03-06 05:25 UTC by erik-sn

This adds notification filters for twitter, currently just two options "All Tweets" and "Only Mentions":

![img](https://i.imgur.com/aHPFfLb.png)

And adds filtering in the twitter notification filtering to:

1. Don't show notifications for the player's own tweets
2. If set to "Only Mentions" doesn't show notifications unless the user's profile name is a substring of the tweet message.

Caveats:

- Weird thing to note, the  `InjectDebugData` in the `TwitterApp.tsx` overwrites the profile name and will cause this "Only Mentions" to not work.
- This adds a new setting so you may have to clear local storage if running this for the first time (not sure)

2021-03-06 05:26 UTC, erik-sn commented on phone/src/ui/hooks/useContextMenu.tsx
> +export interface SettingOption<T = void> {
This generic allows you to optionally specify valid values for the SettingOption

2021-03-06 05:26 UTC, TasoOneAsia commented
> Weird thing to note, the InjectDebugData in the TwitterApp.tsx overwrites the profile name and will cause this "Only Mentions" to not work.

This should never happen when the app is running with process.env.NODE_ENV === 'production'. It will do this in development though.

2021-03-06 05:40 UTC, RockySouthpaw commented
Will test in game sometime in the morning if I don’t get to it tonight. :)

2021-03-06 05:45 UTC, jfrader approved these changes
Lgtm

2021-03-06 06:47 UTC, jfrader requested changes

2021-03-06 06:47 UTC, jfrader commented on phone/src/Phone.tsx
> +  useEffect(() => {
This should be in useTwitterService()

2021-03-06 06:48 UTC, RockySouthpaw commented
PR isn't in a working state. For whatever reason, it's not getting the identifier when creating a profile. This doesn't exist on master or the other twitter PR.
![cmd_BXu7pWF2cL](https://user-images.githubusercontent.com/55056068/110198073-c3428500-7e1d-11eb-91f0-0e9b1935b00e.png)

I double checked my sql and re-installed it and the issue persisted. Unsure what the actual cause of this is.

2021-03-06 15:14 UTC, erik-sn commented on phone/src/Phone.tsx
> +  useEffect(() => {
Updated

2021-03-06 15:17 UTC, erik-sn commented
> This should never happen when the app is running with process.env.NODE_ENV === 'production'. It will do this in development though.

Sorry, yes I should have clarified this is in development - was just warning anyone who was doing testing it might have this behavior

> PR isn't in a working state. For whatever reason, it's not getting the identifier when creating a profile. This doesn't exist on master or the other twitter PR.

I updated `sv_main.ts` to create a profile on player load as you suggested - I wiped the tweets & profile table on my local server and I think this is resolved but I would appreciate it if you can test again. I agree that for some reason ESX is not loading before this fires, I'm not sure why.

2021-03-06 15:48 UTC, RockySouthpaw commented
I’ll test it out when I’m free, yea the whole dependency of esx player loading is a bit annoying since v1 takes a considerably longer amount of time to load in comparatively to the other ESX versions. It’s annoyingly inconvenient to code around a framework that doesn’t load in a reasonable amount of time due to it ditching core FiveM resources.

2021-03-06 16:01 UTC, jfrader approved these changes

2021-03-06 18:21 UTC, RockySouthpaw commented
![image](https://user-images.githubusercontent.com/55056068/110216728-b904a300-7e7e-11eb-8eec-da073d327ef8.png)
New error.

2021-03-06 19:27 UTC, RockySouthpaw commented
Aside from the issue we disucssed, all other functionality with notifications works. Once the issue with creating profiles is fixed then all will be well.

2021-03-07 00:37 UTC, RockySouthpaw approved these changes
PR is fully functional as of the latest ESX fix.

2021-03-07 01:00 UTC, jfrader requested changes

2021-03-07 01:20 UTC, jfrader approved these changes

2021-03-07 01:41 UTC, erik-sn commented on phone/src/apps/twitter/hooks/useTwitterService.ts
> +  useEffect(() => {
updated

2021-03-07 01:42 UTC, erik-sn commented
Ok updated this - I think it is ready @RockySouthpaw

2021-03-07 02:14 UTC, itschip commented
I am not sure if this is just me, but there seems to be an error here. If this something that 'only works ingame', then just remove the whole emulation of that notification.

![image](https://user-images.githubusercontent.com/59088889/110226838-a5931f80-7ef2-11eb-933d-a00ac38c40d3.png)

2021-03-07 02:19 UTC, RockySouthpaw commented
Heres a better screenshot without the weird tint chip applied smh 
![Code_ttGNTpiIx8](https://user-images.githubusercontent.com/55056068/110226991-9d6ebc00-7ec1-11eb-9743-65b29378cb7a.png)

2021-03-07 13:18 UTC, itschip approved these changes
LGTM 👍

2021-03-07 15:25 UTC, merged