Messages bugfix again :D
project-error/new-phone-who-dis pull request #164
Opened 2021-03-11 00:41 UTC by jfrader

Handle offline messages 
Fetch messages and groups when broadcasted

2021-03-11 03:13 UTC, RockySouthpaw commented
**Fixed**
- Offline Messages
 These no longer toss any errors and prints the player is offline correctly.
- Pressing `enter` resulting in the group being created.


This pr doesn't seem to fix the issue with creating a group that already exist as it still loads infinitely. 

Still need to test the following and will edit this after:
- Message notifications loading infinitely when you click on them.
- Message fetching.

2021-03-11 03:38 UTC, jfrader commented
> This pr doesn't seem to fix the issue with creating a group that already exist as it still loads infinitely.
> 
Can you test this again? Pushed a possible fix.

2021-03-11 03:42 UTC, RockySouthpaw commented
Testing now

2021-03-11 03:47 UTC, RockySouthpaw commented
> > This pr doesn't seem to fix the issue with creating a group that already exist as it still loads infinitely.
> 
> Can you test this again? Pushed a possible fix.

Retested. Issue still exist.

2021-03-11 04:48 UTC, RockySouthpaw commented
![image](https://user-images.githubusercontent.com/55056068/110735828-85b47200-81f8-11eb-8cde-fe96a2c3b2bd.png)

Not sure if this was the result of this branch as I currently can't retest it. But this was a result of a notification being triggered with the phone closed.

2021-03-11 13:53 UTC, jfrader commented
No, this is probably new ESX removed branch.

2021-03-11 17:41 UTC, RockySouthpaw commented
This PR is already getting too big. 

> No, this is probably new ESX removed branch.

This was prior to this branch being re-based. Will re test later.

2021-03-12 00:10 UTC, RockySouthpaw commented
Message groups don't work at all now.

2021-03-12 00:19 UTC, RockySouthpaw commented
Looks like this commit is the issue: https://github.com/project-error/new-phone-who-dis/pull/164/commits/ce892c6f5dfb095c41e6b513a6dd59b40537f44c Reverting it fixes

2021-03-13 23:03 UTC, itschip requested changes

2021-03-13 23:03 UTC, itschip commented on phone/src/apps/messages/utils/goToConversation.ts
> +  if (!messageGroup.groupid || !history) return;
Seems to be a typo in 'groupid'. Should it not be 'groupId'?

2021-03-14 11:55 UTC, jfrader commented
Yes, that is the bug

El sáb., 13 mar. 2021 20:03, Christopher Gjelten ***@***.***>
escribió:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In phone/src/apps/messages/utils/goToConversation.ts
> <https://github.com/project-error/new-phone-who-dis/pull/164#discussion_r593812518>
> :
>
> > @@ -1,2 +1,7 @@
> -export const goToConversation = (messageGroup, history) =>
> +import Nui from '../../../os/nui-events/utils/Nui';
> +
> +export const goToConversation = (messageGroup, history) => {
> +  if (!messageGroup.groupid || !history) return;
>
> Seems to be a typo in 'groupid'. Should it not be 'groupId'?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/project-error/new-phone-who-dis/pull/164#pullrequestreview-611644677>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AALVXO4KERY2OLO56YOHKFLTDPVNDANCNFSM4Y7GI5HA>
> .
>

2021-03-19 02:00 UTC, RockySouthpaw approved these changes
Tested and fixes the major issues. Some small ones left to task to simple pr's but the right direction so.

2021-03-19 02:01 UTC, merged