Feature / Add loading state to camera app
project-error/new-phone-who-dis pull request #200
Opened 2021-04-05 23:30 UTC by jfrader

2021-04-05 23:31 UTC, jfrader commented
Needs more testing ^

2021-04-06 09:08 UTC, itschip approved these changes

2021-04-07 03:05 UTC, RockySouthpaw commented
Is this just for pictures being sent?

2021-04-07 03:10 UTC, jfrader commented
This is only for taking a new picture.

2021-04-07 07:59 UTC, itschip requested changes

2021-04-07 07:59 UTC, itschip commented on phone/src/apps/camera/components/grid/GalleryGrid.tsx
> +import { useCamera } from '../../hooks/useCamera';
Remember to change the import in GalleryModal and ShareModal. Those are still trying to import 'usePhotos'

2021-04-09 19:57 UTC, TasoOneAsia approved these changes

2021-04-10 19:03 UTC, itschip approved these changes

2021-04-10 19:19 UTC, merged