fix twitter for light theme
project-error/new-phone-who-dis pull request #64
Opened 2021-02-05 02:57 UTC by erik-sn

Removes coded background and text colors and falls back to theme. Minor styling updates.

2021-02-05 19:31 UTC, TasoOneAsia requested changes
Aside from small changes for cleaning up `makeStyles` when not passing `ThemeObject`, LGTM 👍

2021-02-05 19:31 UTC, TasoOneAsia commented on phone/src/ui/components/Modal.tsx
>  const useStyles = makeStyles(() => ({
Should be able to just pass an object without using an anon function when the `ThemeObject` does not need to be passed.
```ts
makeStyles({})
```

2021-02-05 19:31 UTC, TasoOneAsia commented on phone/src/apps/twitter/components/tweet/TweetMessage.tsx
> +const useStyles = makeStyles(() => ({
Same as above
```ts
makeStyles({})
```

2021-02-06 21:38 UTC, RockySouthpaw commented
Looks fine to me as well. 

https://i.imgur.com/cbCcSch.png

2021-02-06 21:38 UTC, RockySouthpaw approved these changes

2021-02-07 17:52 UTC, erik-sn commented
@TasoOneAsia good call, updated!

2021-02-08 20:13 UTC, merged